trigger:
  branches:
    include:
      - main  # or the desired branch for triggering the pipeline

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Deploy_HUB_DTA
    displayName: 'Deploy Hub VNet to Dev Subscription'
    jobs:
      - job: Deploy_DTA
        displayName: 'Deploy to HUB DTA'
        variables:
          - group: DevVariables  # Variable group for Dev environment
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              azureResourceManagerConnection: '<DevServiceConnection>'  # Service connection for Dev subscription
              subscriptionId: $(subscriptionId)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              templateLocation: 'Linked artifact'
              csmFile: 'hubVnet.bicep'  # Reference to Bicep template
              deploymentMode: 'Incremental'
              parameters: >
                hubVnetName=$(hubVnetName)
                addressPrefix=$(addressPrefix)
                location=$(location)

  # - stage: Deploy_Prod_Hub
  #   displayName: 'Deploy Hub VNet to Prod Subscription'
  #   jobs:
  #     - job: Deploy_Prod
  #       displayName: 'Deploy to Prod'
  #       variables:
  #         - group: ProdVariables  # Variable group for Prod environment
  #       steps:
  #         - task: AzureResourceManagerTemplateDeployment@3
  #           inputs:
  #             azureResourceManagerConnection: '<ProdServiceConnection>'  # Service connection for Prod subscription
  #             subscriptionId: $(subscriptionId)
  #             action: 'Create Or Update Resource Group'
  #             resourceGroupName: $(resourceGroupName)
  #             location: $(location)
  #             templateLocation: 'Linked artifact'
  #             csmFile: 'hubVnet.bicep'
  #             deploymentMode: 'Incremental'
  #             parameters: >
  #               hubVnetName=$(hubVnetName)
  #               addressPrefix=$(addressPrefix)
  #               location=$(location)
