trigger: none

pr: none

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/3.0.38
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.24
    endpoint: SkillsFundingAgency

variables:
- group: RELEASE das-hub-infrastructure

stages:
- stage: Build
  displayName: 'Build and Validate'
  jobs:
  - template: pipeline-templates/job/build.yml

- stage: Deploy_DTA
  dependsOn: Build
  displayName: 'Deploy to DTA'
  variables:
  - group: DTA das-hub-infrastructure
  jobs:
  - template: pipeline-templates/job/deploy-hub.yml
    parameters:
      Environment: DTA
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: Deploy_AT
  dependsOn: Build
  displayName: 'Deploy to AT'
  variables:
  - group: AT das-hub-infrastructure
  jobs:
  - template: pipeline-templates/job/deploy-hub.yml
    parameters:
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: Deploy_TEST
  dependsOn: Build
  displayName: 'Deploy to TEST'
  variables:
  - group: TEST das-hub-infrastructure
  jobs:
  - template: pipeline-templates/job/deploy-hub.yml
    parameters:
      Environment: TEST
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: Deploy_TEST2
  dependsOn: Build
  displayName: 'Deploy to TEST2'
  variables:
  - group: TEST2 das-hub-infrastructure
  jobs:
  - template: pipeline-templates/job/deploy-hub.yml
    parameters:
      Environment: TEST2
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: Deploy_DEMO
  dependsOn: Build
  displayName: 'Deploy to DEMO'
  variables:
  - group: DEMO das-hub-infrastructure
  jobs:
  - template: pipeline-templates/job/deploy-hub.yml
    parameters:
      Environment: DEMO
      ServiceConnection: SFA-DAS-DevTest-ARM

- stage: Deploy_PP
  dependsOn: Build
  displayName: 'Deploy to PP'
  variables:
  - group: PP das-hub-infrastructure
  jobs:
  - template: pipeline-templates/job/deploy-hub.yml
    parameters:
      Environment: PREPROD
      ServiceConnection: SFA-DIG-PreProd-ARM

# - stage: Deploy_MO
#   dependsOn: Build
#   displayName: 'Deploy to MO'
#   variables:
#   - group: MO das-hub-infrastructure
#   jobs:
#   - template: pipeline-templates/job/deploy-hub.yml
#     parameters:
#       Environment: MO
#       ServiceConnection: SFA-ASM-ModelOffice-ARM

# - stage: Deploy_PRD
#   dependsOn: Build
#   displayName: 'Deploy to PRD'
#   variables:
#   - group: PRD das-hub-infrastructure
#   jobs:
#   - template: pipeline-templates/job/deploy-hub.yml
#     parameters:
#       Environment: PRD
#       ServiceConnection: SFA-DIG-Prod-ARM
