trigger: none

parameters:
- name: firewallSubnetName
  displayName: 'Azure Firewall Subnet Name'
  type: string
  default: 'AzureFirewallSubnet'
  
- name: environment
  displayName: 'Select Environment'
  type: string
  default: 'dta'
  values:
  - dta
  - at
  - demo
  - test
  - test2
  - prod

resources:
  repositories:
  - repository: das-hub-infrastructure
    type: github
    endpoint: SkillsFundingAgency
    name: SkillsFundingAgency/das-hub-infrastructure
    ref: main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DTA
  displayName: 'Deploy to DTA Environment'
  condition: eq('${{ parameters.environment }}', 'dta')
  variables:
  - name: selectedEnvironment
    value: ${{ parameters.environment }}
  - group: Dev-HubVariables
  jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to DTA'
    steps:
    - checkout: das-hub-infrastructure
      displayName: 'Checkout Repository'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SFA-DAS-DevTest-ARM'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |+
          # Check if resource group exists, create if not
          resourceGroupExists=$(az group exists --name $(resourceGroupName))

          if [ "$resourceGroupExists" = false ]; then
            echo "Resource group $(resourceGroupName) doesn't exist. Creating..."
            az group create --name $(resourceGroupName) --location $(location)  --tags "Environment=Dev/Test" "Product=AS Manage your Apprenticeships" "Parent Business=Apprenticeships" "Portfolio=Education and Skills Funding Agency" "Product=AS Manage your Apprenticeships" "Service=Apprenticeships" "Service Line=Apprenticeships" "Service Offering=AS Manage your Apprenticeships"
            sleep 30
          else
            echo "Resource group $(resourceGroupName) already exists."
          fi

          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file config/hub.template.json \
            --parameters publicIPAddressName=$(publicIPAddressName) \
                        natGatewayName=$(natGatewayName) \
                        firewallName=$(firewallName) \
                        firewallPublicIpName=$(firewallPublicIpName) \
                        vnetName=$(vnetName) \
                        armVnetAddressSpaceCIDR=$(armVnetAddressSpaceCIDR) \
                        subnet1Name=$(subnet1Name) \
                        subnet1Prefix=$(subnet1Prefix) \
                        subnet2Name=$(subnet2Name) \
                        subnet2Prefix=$(subnet2Prefix) \
                        firewallPolicy1Name=$(firewallPolicy1Name) \
                        firewallPolicy2Name=$(firewallPolicy2Name) \
                        location=$(location) \
                        networkRuleCollectionGroupName=NetworkGroup \
                        applicationRuleCollectionGroupName=AppGroup \
                        rulesFileUri="@./config/firewall_rules.json"


                      
- stage: AT
  displayName: 'Deploy to AT Environment'
  condition: eq('${{ parameters.environment }}', 'at')
  variables:
  - name: selectedEnvironment
    value: ${{ parameters.environment }}
  - group: AT-HubVariables
  jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to AT'
    steps:
    - checkout: das-hub-infrastructure
      displayName: 'Checkout Repository'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SFA-DAS-DevTest-ARM'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |+
          # Check if resource group exists, create if not
          resourceGroupExists=$(az group exists --name $(resourceGroupName))

          if [ "$resourceGroupExists" = false ]; then
            echo "Resource group $(resourceGroupName) doesn't exist. Creating..."
            az group create --name $(resourceGroupName) --location $(location)  --tags "Environment=Dev/Test" "Product=AS Manage your Apprenticeships" "Parent Business=Apprenticeships" "Portfolio=Education and Skills Funding Agency" "Product=AS Manage your Apprenticeships" "Service=Apprenticeships" "Service Line=Apprenticeships" "Service Offering=AS Manage your Apprenticeships"
            sleep 30
          else
            echo "Resource group $(resourceGroupName) already exists."
          fi
          # Skip operations on AzureFirewallSubnet
          if [[ "$(subnet1Name)" == "${{ parameters.firewallSubnetName }}" ]]; then
            echo "Skipping update for Azure Firewall Subnet: $(subnet1Name)"
          else

          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file config/hub.template.json \
            --parameters publicIPAddressName=$(publicIPAddressName) \
                        natGatewayName=$(natGatewayName) \
                        firewallName=$(firewallName) \
                        firewallPublicIpName=$(firewallPublicIpName) \
                        vnetName=$(vnetName) \
                        armVnetAddressSpaceCIDR=$(armVnetAddressSpaceCIDR) \
                        subnet1Name=$(subnet1Name) \
                        subnet1Prefix=$(subnet1Prefix) \
                        subnet2Name=$(subnet2Name) \
                        subnet2Prefix=$(subnet2Prefix) \
                        firewallPolicy1Name=$(firewallPolicy1Name) \
                        firewallPolicy2Name=$(firewallPolicy2Name) \
                        location=$(location) \
                        networkRuleCollectionGroupName=NetworkGroup \
                        applicationRuleCollectionGroupName=AppGroup \
                        rulesFileUri="@./config/firewall_rules.json"

- stage: Demo
  displayName: 'Deploy to Demo Environment'
  condition: eq('${{ parameters.environment }}', 'demo')
  variables:
  - name: selectedEnvironment
    value: ${{ parameters.environment }}
  - group: Demo-HubVariables
  jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to Demo'
    steps:
    - checkout: das-hub-infrastructure
      displayName: 'Checkout Repository'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SFA-DAS-DevTest-ARM'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |+
          # Check if resource group exists, create if not
          resourceGroupExists=$(az group exists --name $(resourceGroupName))

          if [ "$resourceGroupExists" = false ]; then
            echo "Resource group $(resourceGroupName) doesn't exist. Creating..."
            az group create --name $(resourceGroupName) --location $(location)  --tags "Environment=Dev/Test" "Product=AS Manage your Apprenticeships" "Parent Business=Apprenticeships" "Portfolio=Education and Skills Funding Agency" "Product=AS Manage your Apprenticeships" "Service=Apprenticeships" "Service Line=Apprenticeships" "Service Offering=AS Manage your Apprenticeships"
            sleep 30
          else
            echo "Resource group $(resourceGroupName) already exists."
          fi

          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file config/hub.template.json \
            --parameters publicIPAddressName=$(publicIPAddressName) \
                        natGatewayName=$(natGatewayName) \
                        firewallName=$(firewallName) \
                        firewallPublicIpName=$(firewallPublicIpName) \
                        vnetName=$(vnetName) \
                        armVnetAddressSpaceCIDR=$(armVnetAddressSpaceCIDR) \
                        subnet1Name=$(subnet1Name) \
                        subnet1Prefix=$(subnet1Prefix) \
                        subnet2Name=$(subnet2Name) \
                        subnet2Prefix=$(subnet2Prefix) \
                        firewallPolicy1Name=$(firewallPolicy1Name) \
                        firewallPolicy2Name=$(firewallPolicy2Name) \
                        location=$(location)

- stage: Test
  displayName: 'Deploy to Test Environment'
  condition: eq('${{ parameters.environment }}', 'test')
  variables:
  - name: selectedEnvironment
    value: ${{ parameters.environment }}
  - group: Test-HubVariables
  jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to Test'
    steps:
    - checkout: das-hub-infrastructure
      displayName: 'Checkout Repository'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SFA-DAS-DevTest-ARM'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |+
          # Check if resource group exists, create if not
          resourceGroupExists=$(az group exists --name $(resourceGroupName))

          if [ "$resourceGroupExists" = false ]; then
            echo "Resource group $(resourceGroupName) doesn't exist. Creating..."
            az group create --name $(resourceGroupName) --location $(location)  --tags "Environment=Dev/Test" "Product=AS Manage your Apprenticeships" "Parent Business=Apprenticeships" "Portfolio=Education and Skills Funding Agency" "Product=AS Manage your Apprenticeships" "Service=Apprenticeships" "Service Line=Apprenticeships" "Service Offering=AS Manage your Apprenticeships"
            sleep 30
          else
            echo "Resource group $(resourceGroupName) already exists."
          fi

          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file config/hub.template.json \
            --parameters publicIPAddressName=$(publicIPAddressName) \
                        natGatewayName=$(natGatewayName) \
                        firewallName=$(firewallName) \
                        firewallPublicIpName=$(firewallPublicIpName) \
                        vnetName=$(vnetName) \
                        armVnetAddressSpaceCIDR=$(armVnetAddressSpaceCIDR) \
                        subnet1Name=$(subnet1Name) \
                        subnet1Prefix=$(subnet1Prefix) \
                        subnet2Name=$(subnet2Name) \
                        subnet2Prefix=$(subnet2Prefix) \
                        firewallPolicy1Name=$(firewallPolicy1Name) \
                        firewallPolicy2Name=$(firewallPolicy2Name) \
                        location=$(location)

- stage: Test2
  displayName: 'Deploy to Test2 Environment'
  condition: eq('${{ parameters.environment }}', 'test2')
  variables:
  - name: selectedEnvironment
    value: ${{ parameters.environment }}
  - group: Test2-HubVariables
  jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to Test2'
    steps:
    - checkout: das-hub-infrastructure
      displayName: 'Checkout Repository'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SFA-DAS-DevTest-ARM'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |+
          # Check if resource group exists, create if not
          resourceGroupExists=$(az group exists --name $(resourceGroupName))

          if [ "$resourceGroupExists" = false ]; then
            echo "Resource group $(resourceGroupName) doesn't exist. Creating..."
            az group create --name $(resourceGroupName) --location $(location)  --tags "Environment=Dev/Test" "Product=AS Manage your Apprenticeships" "Parent Business=Apprenticeships" "Portfolio=Education and Skills Funding Agency" "Product=AS Manage your Apprenticeships" "Service=Apprenticeships" "Service Line=Apprenticeships" "Service Offering=AS Manage your Apprenticeships"
            sleep 30
          else
            echo "Resource group $(resourceGroupName) already exists."
          fi

          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file config/hub.template.json \
            --parameters publicIPAddressName=$(publicIPAddressName) \
                        natGatewayName=$(natGatewayName) \
                        firewallName=$(firewallName) \
                        firewallPublicIpName=$(firewallPublicIpName) \
                        vnetName=$(vnetName) \
                        armVnetAddressSpaceCIDR=$(armVnetAddressSpaceCIDR) \
                        subnet1Name=$(subnet1Name) \
                        subnet1Prefix=$(subnet1Prefix) \
                        subnet2Name=$(subnet2Name) \
                        subnet2Prefix=$(subnet2Prefix) \
                        firewallPolicy1Name=$(firewallPolicy1Name) \
                        firewallPolicy2Name=$(firewallPolicy2Name) \
                        location=$(location)


                  
- stage: Prod
  displayName: 'Deploy to Prod Environment'
  condition: eq('${{ parameters.environment }}', 'prod')
  variables:
  - name: selectedEnvironment
    value: ${{ parameters.environment }}
  - group: Prod-HubVariables
  jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to Prod'
    steps:
    - checkout: das-hub-infrastructure
      displayName: 'Checkout Repository'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SFA-DAS-DevTest-ARM'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Check if resource group exists, create if not
          resourceGroupExists=$(az group exists --name $(resourceGroupName))

          if [ "$resourceGroupExists" = false ]; then
            echo "Resource group $(resourceGroupName) doesn't exist. Creating..."
            az group create --name $(resourceGroupName) --location $(location)  --tags "Environment=Dev/Test" "Product=AS Manage your Apprenticeships" "Parent Business=Apprenticeships" "Portfolio=Education and Skills Funding Agency" "Product=AS Manage your Apprenticeships" "Service=Apprenticeships" "Service Line=Apprenticeships" "Service Offering=AS Manage your Apprenticeships"
            sleep 30
          else
            echo "Resource group $(resourceGroupName) already exists."
          fi

          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file config/hub.template.json \
            --parameters publicIPAddressName=$(publicIPAddressName) \
                        natGatewayName=$(natGatewayName) \
                        firewallName=$(firewallName) \
                        firewallPublicIpName=$(firewallPublicIpName) \
                        vnetName=$(vnetName) \
                        armVnetAddressSpaceCIDR=$(armVnetAddressSpaceCIDR) \
                        subnet1Name=$(subnet1Name) \
                        subnet1Prefix=$(subnet1Prefix) \
                        subnet2Name=$(subnet2Name) \
                        subnet2Prefix=$(subnet2Prefix) \
                        firewallPolicy1Name=$(firewallPolicy1Name) \
                        firewallPolicy2Name=$(firewallPolicy2Name) \
                        location=$(location)
